// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

// Embedded application icon
//
//go:embed app_icon.png
var applicationIconData []byte
var applicationIcon = &fyne.StaticResource{
	StaticName:    "app_icon.png",
	StaticContent: applicationIconData,
}
