// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

// Embedded application icon
//
//go:embed app_icon.png
var applicationIconData []byte
var applicationIcon = &fyne.StaticResource{
	StaticName:    "app_icon.png",
	StaticContent: applicationIconData,
}

// Embedded developer icon
//
//go:embed lordofscripts_logo_small.png
var developerIconData []byte
var developerIcon = &fyne.StaticResource{
	StaticName:    "lordofscripts_logo_small.png",
	StaticContent: developerIconData,
}
